### ISSUE TITLE
Add Mentor model

### ISSUE THREAD

**Issue by 01walid** [annaba-tech/techdays#1]
I already created an initial version of the Mentor model in DatoCMS (with name & bio), just add the following fields: 

- Job Title (required)
- Photo
- Github
- Twitter
- Website/Blog
- Facebook
- LinkedIn
- Youtube

**Comment by mabouguerra** [comment]
Done. Added the following fields as well:

* Slug (required, to appear on the URL e.g. annaba.tech/mentors/slug).
* Company.

**Comment by 01walid** [comment]
@mabouguerra cool, thanks!
